// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: slabone/slabone/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateSlab struct {
	Creator            string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	OriginatorSocialId string `protobuf:"bytes,2,opt,name=originatorSocialId,proto3" json:"originatorSocialId,omitempty"`
	DirectedTowards    string `protobuf:"bytes,3,opt,name=directedTowards,proto3" json:"directedTowards,omitempty"`
	Assertion          string `protobuf:"bytes,4,opt,name=assertion,proto3" json:"assertion,omitempty"`
	UriOriginator      string `protobuf:"bytes,5,opt,name=uriOriginator,proto3" json:"uriOriginator,omitempty"`
}

func (m *MsgCreateSlab) Reset()         { *m = MsgCreateSlab{} }
func (m *MsgCreateSlab) String() string { return proto.CompactTextString(m) }
func (*MsgCreateSlab) ProtoMessage()    {}
func (*MsgCreateSlab) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e537496514f213a, []int{0}
}
func (m *MsgCreateSlab) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateSlab) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateSlab.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateSlab) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateSlab.Merge(m, src)
}
func (m *MsgCreateSlab) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateSlab) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateSlab.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateSlab proto.InternalMessageInfo

func (m *MsgCreateSlab) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateSlab) GetOriginatorSocialId() string {
	if m != nil {
		return m.OriginatorSocialId
	}
	return ""
}

func (m *MsgCreateSlab) GetDirectedTowards() string {
	if m != nil {
		return m.DirectedTowards
	}
	return ""
}

func (m *MsgCreateSlab) GetAssertion() string {
	if m != nil {
		return m.Assertion
	}
	return ""
}

func (m *MsgCreateSlab) GetUriOriginator() string {
	if m != nil {
		return m.UriOriginator
	}
	return ""
}

type MsgCreateSlabResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateSlabResponse) Reset()         { *m = MsgCreateSlabResponse{} }
func (m *MsgCreateSlabResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateSlabResponse) ProtoMessage()    {}
func (*MsgCreateSlabResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e537496514f213a, []int{1}
}
func (m *MsgCreateSlabResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateSlabResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateSlabResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateSlabResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateSlabResponse.Merge(m, src)
}
func (m *MsgCreateSlabResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateSlabResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateSlabResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateSlabResponse proto.InternalMessageInfo

func (m *MsgCreateSlabResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgInspectSlab struct {
	Creator        string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	VetterSocialId string `protobuf:"bytes,2,opt,name=vetterSocialId,proto3" json:"vetterSocialId,omitempty"`
	VettingNote    string `protobuf:"bytes,3,opt,name=vettingNote,proto3" json:"vettingNote,omitempty"`
	UriVetter      string `protobuf:"bytes,4,opt,name=uriVetter,proto3" json:"uriVetter,omitempty"`
	Id             uint64 `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgInspectSlab) Reset()         { *m = MsgInspectSlab{} }
func (m *MsgInspectSlab) String() string { return proto.CompactTextString(m) }
func (*MsgInspectSlab) ProtoMessage()    {}
func (*MsgInspectSlab) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e537496514f213a, []int{2}
}
func (m *MsgInspectSlab) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInspectSlab) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInspectSlab.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInspectSlab) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInspectSlab.Merge(m, src)
}
func (m *MsgInspectSlab) XXX_Size() int {
	return m.Size()
}
func (m *MsgInspectSlab) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInspectSlab.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInspectSlab proto.InternalMessageInfo

func (m *MsgInspectSlab) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgInspectSlab) GetVetterSocialId() string {
	if m != nil {
		return m.VetterSocialId
	}
	return ""
}

func (m *MsgInspectSlab) GetVettingNote() string {
	if m != nil {
		return m.VettingNote
	}
	return ""
}

func (m *MsgInspectSlab) GetUriVetter() string {
	if m != nil {
		return m.UriVetter
	}
	return ""
}

func (m *MsgInspectSlab) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgInspectSlabResponse struct {
}

func (m *MsgInspectSlabResponse) Reset()         { *m = MsgInspectSlabResponse{} }
func (m *MsgInspectSlabResponse) String() string { return proto.CompactTextString(m) }
func (*MsgInspectSlabResponse) ProtoMessage()    {}
func (*MsgInspectSlabResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e537496514f213a, []int{3}
}
func (m *MsgInspectSlabResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInspectSlabResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInspectSlabResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInspectSlabResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInspectSlabResponse.Merge(m, src)
}
func (m *MsgInspectSlabResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgInspectSlabResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInspectSlabResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInspectSlabResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateSlab)(nil), "slabone.slabone.MsgCreateSlab")
	proto.RegisterType((*MsgCreateSlabResponse)(nil), "slabone.slabone.MsgCreateSlabResponse")
	proto.RegisterType((*MsgInspectSlab)(nil), "slabone.slabone.MsgInspectSlab")
	proto.RegisterType((*MsgInspectSlabResponse)(nil), "slabone.slabone.MsgInspectSlabResponse")
}

func init() { proto.RegisterFile("slabone/slabone/tx.proto", fileDescriptor_8e537496514f213a) }

var fileDescriptor_8e537496514f213a = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x4a, 0xfb, 0x40,
	0x10, 0xc7, 0xbb, 0xfd, 0xf3, 0xfb, 0xd1, 0x29, 0x6d, 0x61, 0x41, 0x5d, 0x8a, 0xc4, 0x52, 0xa4,
	0xed, 0x29, 0xa2, 0xbe, 0x81, 0x9e, 0x7a, 0xa8, 0x42, 0x5b, 0x14, 0xbc, 0xa5, 0xc9, 0x10, 0x16,
	0x4a, 0x36, 0xec, 0x6e, 0xb5, 0xbe, 0x85, 0xcf, 0xe0, 0x33, 0xf8, 0x0e, 0x7a, 0xec, 0xd1, 0xa3,
	0xb4, 0x2f, 0x22, 0x59, 0x92, 0x34, 0x09, 0xc5, 0x9e, 0x96, 0xf9, 0xce, 0x77, 0x92, 0xf9, 0xcc,
	0x0c, 0x30, 0xb5, 0x70, 0xe6, 0x22, 0xc0, 0x8b, 0xe4, 0xd5, 0x2b, 0x3b, 0x94, 0x42, 0x0b, 0xda,
	0x8e, 0x15, 0x3b, 0x7e, 0x7b, 0x9f, 0x04, 0x9a, 0x63, 0xe5, 0xdf, 0x4a, 0x74, 0x34, 0x4e, 0x17,
	0xce, 0x9c, 0x32, 0xf8, 0xef, 0x46, 0x91, 0x90, 0x8c, 0x74, 0xc9, 0xb0, 0x3e, 0x49, 0x42, 0x6a,
	0x03, 0x15, 0x92, 0xfb, 0x3c, 0x88, 0xa2, 0xa9, 0x70, 0xb9, 0xb3, 0x18, 0x79, 0xac, 0x6c, 0x4c,
	0x7b, 0x32, 0x74, 0x08, 0x6d, 0x8f, 0x4b, 0x74, 0x35, 0x7a, 0x33, 0xf1, 0xe2, 0x48, 0x4f, 0xb1,
	0x8a, 0x31, 0x17, 0x65, 0x7a, 0x0a, 0x75, 0x47, 0x29, 0x94, 0x9a, 0x8b, 0x80, 0x55, 0x8d, 0x67,
	0x27, 0xd0, 0x73, 0x68, 0x2e, 0x25, 0xbf, 0x4f, 0x7f, 0xc0, 0x6a, 0xc6, 0x91, 0x17, 0x7b, 0x03,
	0x38, 0xca, 0x81, 0x4c, 0x50, 0x85, 0x22, 0x50, 0x48, 0x5b, 0x50, 0xe6, 0x9e, 0x61, 0xa9, 0x4e,
	0xca, 0xdc, 0xeb, 0xbd, 0x13, 0x68, 0x8d, 0x95, 0x3f, 0x0a, 0x54, 0x88, 0xae, 0x3e, 0xc0, 0xdc,
	0x87, 0xd6, 0x33, 0x6a, 0x8d, 0x45, 0xde, 0x82, 0x4a, 0xbb, 0xd0, 0x88, 0x14, 0x1e, 0xf8, 0x77,
	0x42, 0x63, 0xcc, 0x99, 0x95, 0x22, 0xc6, 0xa5, 0xe4, 0x0f, 0xa6, 0x2c, 0x61, 0x4c, 0x85, 0xb8,
	0xc9, 0x5a, 0xda, 0x24, 0x83, 0xe3, 0x7c, 0x8f, 0x09, 0xce, 0xd5, 0x07, 0x81, 0xca, 0x58, 0xf9,
	0x74, 0x06, 0x90, 0xd9, 0x9a, 0x65, 0x17, 0x36, 0x6b, 0xe7, 0x86, 0xd1, 0xe9, 0xff, 0x9d, 0x4f,
	0x87, 0xf5, 0x08, 0x8d, 0xec, 0x60, 0xce, 0xf6, 0x95, 0x65, 0x0c, 0x9d, 0xc1, 0x01, 0x43, 0xf2,
	0xe1, 0x9b, 0xcb, 0xaf, 0x8d, 0x45, 0xd6, 0x1b, 0x8b, 0xfc, 0x6c, 0x2c, 0xf2, 0xb6, 0xb5, 0x4a,
	0xeb, 0xad, 0x55, 0xfa, 0xde, 0x5a, 0xa5, 0xa7, 0x93, 0xe4, 0x4a, 0x57, 0xbb, 0x7b, 0x7d, 0x0d,
	0x51, 0xcd, 0xff, 0x99, 0x9b, 0xbd, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x07, 0x15, 0x89, 0x82,
	0xcf, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateSlab(ctx context.Context, in *MsgCreateSlab, opts ...grpc.CallOption) (*MsgCreateSlabResponse, error)
	InspectSlab(ctx context.Context, in *MsgInspectSlab, opts ...grpc.CallOption) (*MsgInspectSlabResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateSlab(ctx context.Context, in *MsgCreateSlab, opts ...grpc.CallOption) (*MsgCreateSlabResponse, error) {
	out := new(MsgCreateSlabResponse)
	err := c.cc.Invoke(ctx, "/slabone.slabone.Msg/CreateSlab", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) InspectSlab(ctx context.Context, in *MsgInspectSlab, opts ...grpc.CallOption) (*MsgInspectSlabResponse, error) {
	out := new(MsgInspectSlabResponse)
	err := c.cc.Invoke(ctx, "/slabone.slabone.Msg/InspectSlab", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateSlab(context.Context, *MsgCreateSlab) (*MsgCreateSlabResponse, error)
	InspectSlab(context.Context, *MsgInspectSlab) (*MsgInspectSlabResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateSlab(ctx context.Context, req *MsgCreateSlab) (*MsgCreateSlabResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSlab not implemented")
}
func (*UnimplementedMsgServer) InspectSlab(ctx context.Context, req *MsgInspectSlab) (*MsgInspectSlabResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InspectSlab not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateSlab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateSlab)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateSlab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slabone.slabone.Msg/CreateSlab",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateSlab(ctx, req.(*MsgCreateSlab))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_InspectSlab_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInspectSlab)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).InspectSlab(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slabone.slabone.Msg/InspectSlab",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).InspectSlab(ctx, req.(*MsgInspectSlab))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "slabone.slabone.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSlab",
			Handler:    _Msg_CreateSlab_Handler,
		},
		{
			MethodName: "InspectSlab",
			Handler:    _Msg_InspectSlab_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "slabone/slabone/tx.proto",
}

func (m *MsgCreateSlab) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateSlab) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateSlab) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UriOriginator) > 0 {
		i -= len(m.UriOriginator)
		copy(dAtA[i:], m.UriOriginator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.UriOriginator)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Assertion) > 0 {
		i -= len(m.Assertion)
		copy(dAtA[i:], m.Assertion)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Assertion)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.DirectedTowards) > 0 {
		i -= len(m.DirectedTowards)
		copy(dAtA[i:], m.DirectedTowards)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DirectedTowards)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OriginatorSocialId) > 0 {
		i -= len(m.OriginatorSocialId)
		copy(dAtA[i:], m.OriginatorSocialId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OriginatorSocialId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateSlabResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateSlabResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateSlabResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgInspectSlab) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInspectSlab) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInspectSlab) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x28
	}
	if len(m.UriVetter) > 0 {
		i -= len(m.UriVetter)
		copy(dAtA[i:], m.UriVetter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.UriVetter)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.VettingNote) > 0 {
		i -= len(m.VettingNote)
		copy(dAtA[i:], m.VettingNote)
		i = encodeVarintTx(dAtA, i, uint64(len(m.VettingNote)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.VetterSocialId) > 0 {
		i -= len(m.VetterSocialId)
		copy(dAtA[i:], m.VetterSocialId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.VetterSocialId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgInspectSlabResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInspectSlabResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInspectSlabResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateSlab) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.OriginatorSocialId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DirectedTowards)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Assertion)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.UriOriginator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateSlabResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgInspectSlab) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.VetterSocialId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.VettingNote)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.UriVetter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgInspectSlabResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateSlab) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateSlab: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateSlab: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginatorSocialId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OriginatorSocialId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DirectedTowards", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DirectedTowards = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Assertion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Assertion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UriOriginator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UriOriginator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateSlabResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateSlabResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateSlabResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInspectSlab) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInspectSlab: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInspectSlab: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VetterSocialId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VetterSocialId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VettingNote", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VettingNote = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UriVetter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UriVetter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInspectSlabResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInspectSlabResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInspectSlabResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
