version: 1
accounts:
- name: alice
  coins:
  - 100000000nulltoken
  - 200000000stake
- name: bob
  coins:
  - 300000000nulltoken
  - 300000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 10nulltoken
  port: 4500
validators:
- name: alice
  bonded: 100000000stake

